### ISSUE TITLE
open: command not found

### ISSUE THREAD

**Issue by alexangas** [luckman212/1password-csv-fix#1]
Firstly, thank you so much for this script. Without meaning any offence, I was not expecting something so professional. It's very well done, kudos!

An issue I encountered when running `./1password-csv-fix.sh --fix 6fb47idj567csrhpi7ytsvpk5a`

> ./1password-csv-fix.sh: line 97: open: command not found

I'm running the script on Linux - that may be why. The script had already successfully corrected the entry in 1Password.

**Comment by luckman212** [comment]
Another good catch. Yes `open` is a macOS command. Not even sure it makes sense on Linux which in some cases might not even have a window manager running. I will need to rethink that section of the program, and see if there's an equivalent that would work generically on Linux.

**Comment by luckman212** [comment]
Not 100% sure about this, because I had to spin up a test Ubuntu environment to try it, but I am hopeful this works. Please try [v1.0.1](https://github.com/luckman212/1password-csv-fix/releases/tag/1.0.1) and let me know...

**Comment by alexangas** [comment]
Yes this works now - thanks!

A minor suggestion - perhaps the user doesn't care about reviewing the fixed item and could opt in to the open behaviour.

**Comment by luckman212** [comment]
@alexangas In the latest version [1.0.2](https://github.com/luckman212/1password-csv-fix/releases/tag/1.0.2), I've made the "open after fixing" behavior optional. Just change the var on line 23 to `OPEN_AFTER_FIX=false`.
