### ISSUE TITLE
Ordinary users can't write to /tmp

### ISSUE THREAD

**Issue by alexangas** [luckman212/1password-csv-fix#3]
Running with a "Standard" user under Fedora (KDE) throws an error, as the user does not have permission to write to `/tmp`.

Obviously no issue with an "Administrator" user.

(By the way - this is the last issue, everything else has worked great. Thank you so much once again!)

**Comment by luckman212** [comment]
I'm looking at https://superuser.com/questions/332610/where-is-the-temporary-directory-in-linux trying to figure out what the best practice is here.

Seems like we should check `$XDG_RUNTIME_DIR` and use that if it's writeable.

**Comment by luckman212** [comment]
@alexangas Would you mind trying [v1.0.2](https://github.com/luckman212/1password-csv-fix/releases/tag/1.0.2) and let me know if that does the trick?

**Comment by luckman212** [comment]
@alexangas Were you able to check?

**Comment by alexangas** [comment]
I don't have any more vaults to test conversions on, however I was able to look at this directory and test writing to it as the standard user. I think you are all good to use that variable for this purpose!

![image](https://github.com/luckman212/1password-csv-fix/assets/132198/6f63a068-07bb-4e80-863d-241c6342e79b)

The `test.txt` is the file written as the standard user. Everything else gives you an idea of what else is in that directory. It looks appropriate.

**Comment by luckman212** [comment]
Great, I'll close this out then.

Hope you were able to make use of the script. Your feedback was helpful! If you have any other ideas let me know.
